# Generated by Django 4.0.6 on 2022-07-20 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], max_length=35)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('task', 'Задача'), ('bug', 'Ошибка'), ('enhancement', 'улучшение')], max_length=35)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
                'db_table': 'types',
            },
        ),
        migrations.CreateModel(
            name='Sketchpad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('summary', models.CharField(default='No summary', max_length=50, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Полное описание')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='webapp.status', verbose_name='Статус')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='webapp.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'Список задач',
                'db_table': 'sketchpad',
            },
        ),
    ]
