# Generated by Django 4.0.6 on 2022-07-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_type_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sketchpad',
            name='type',
        ),
        migrations.AddField(
            model_name='sketchpad',
            name='type',
            field=models.ManyToManyField(related_name='issues', to='webapp.type', verbose_name='Тип'),
        ),
    ]
