# Generated by Django 4.0.6 on 2022-08-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('create_project', 'Создать проект'), ('remove_project', 'Удалить проект'), ('update_project', 'Редактировать проект'), ('create_issue', 'Создать задачу'), ('delete_issue', 'Удалить задачу'), ('update_issue', 'Редактировать задачу'), ('add_user', 'Добавить пользователя'), ('view_users', 'Просмотр пользователей')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
